/*
 * File: app/store/EmployeeStore.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PixonicTeam.store.EmployeeStore', {
    extend: 'Ext.data.Store',

    requires: [
        'PixonicTeam.model.Employee',
        'Ext.util.Grouper'
    ],

    config: {
        autoLoad: true,
        data: [
            {
                lastname: 'Kansas'
            },
            {
                lastname: 'Kelly'
            },
            {
                lastname: 'Potter Lake'
            },
            {
                lastname: 'University'
            },
            {
                lastname: 'Uta'
            },
            {
                lastname: 'Lawrence'
            },
            {
                lastname: 'Leon'
            },
            {
                lastname: 'Lion'
            }
        ],
        model: 'PixonicTeam.model.Employee',
        storeId: 'EmployeeStore',
        grouper: {
            groupFn: function(item) {
                return item.get('lastname').substr(0, 1);
            },
            sortProperty: 'lastname'
        },
        listeners: [
            {
                fn: 'onArraystoreLoad',
                event: 'load'
            }
        ]
    },

    onArraystoreLoad: function(store, records, successful, operation, eOpts) {
            console.log("Store load success? " + successful );
            console.log(operation);
    }

});