/*
 * File: app/store/EmployeeStore.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PixonicTeam.store.EmployeeStore', {
    extend: 'Ext.data.Store',

    requires: [
        'PixonicTeam.model.Employee',
        'Ext.util.Grouper'
    ],

    config: {
        autoLoad: true,
        data: [
            {
                name: 'Ананьев Александр',
                email: 'email@pixonic.ru',
                office: 'Москва',
                post: '2D концепт-художник',
                phone: '(933) 045-1869',
                skype: 'necessitatibus',
                photo: 'http://aimed.spb.ru/images/cms/thumbs/142e21f5603e46b2330254502ddbcabba75dc90f/sperm_80_80_5_80.png?key=api',
                idFacebook: '',
                idInstagram: '',
                idTwitter: '',
                idVKontakte: '',
                holidayBegin: 'est',
                holidayEnd: 'alias',
                regDate: 'saepe',
                info: 'О себе!'
            },
            {
                name: 'Холин Роман',
                email: 'r.holin@pixonic.ru',
                office: 'Белгород',
                post: 'Гейм-дизайнер',
                phone: '(968) 921-48-37',
                skype: 'ripenemy',
                photo: 'http://aimed.spb.ru/images/cms/thumbs/142e21f5603e46b2330254502ddbcabba75dc90f/sperm_80_80_5_80.png?key=api',
                idFacebook: 'https://www.facebook.com/roman.kholin.56',
                idInstagram: 'https://www.instagram.com/ripenemy/',
                idTwitter: 'https://twitter.com/RIPEnemy',
                idVKontakte: 'http://vk.com/r.kholin',
                holidayBegin: 'ratione',
                holidayEnd: 'commodi',
                regDate: 'aut',
                info: 'О себе!О себе!О себе!О себе!О себе!О себе!О себе!О себе!О себе!О себе!О себе!О себе!О себе!О себе!О себе!О себе!О себе!О себе!О себе!О себе!О себе!'
            },
            {
                name: 'Матюха Дарья',
                email: 'matyukha@pixonic.ru',
                office: 'Белгород',
                post: 'Программист',
                phone: '(980) 387-08-01',
                skype: 'magnolia9102',
                photo: 'http://aimed.spb.ru/images/cms/thumbs/142e21f5603e46b2330254502ddbcabba75dc90f/sperm_80_80_5_80.png?key=api',
                idFacebook: 'https://www.facebook.com/profile.php?id=100006846364642',
                idInstagram: 'https://www.instagram.com/ifsogirl91/',
                idTwitter: '',
                idVKontakte: 'https://vk.com/id5710116',
                holidayBegin: 'ratione',
                holidayEnd: 'commodi',
                regDate: 'aut',
                info: 'О себе!О себе!О себе!О себе!О себе!О себе!О себе!О себе!О себе!О себе!О себе!О себе!О себе!О себе!О себе!О себе!О себе!О себе!О себе!О себе!О себе!О себе!О себе!О себе!О себе!О себе!О себе!О себе!О себе!О себе!О себе!О себе!О себе!О себе!О себе!О себе!О себе!О себе!О себе!О себе!О себе!О себе!'
            }
        ],
        model: 'PixonicTeam.model.Employee',
        storeId: 'EmployeeStore',
        grouper: {
            groupFn: function(item) {
                return item.get('name').substr(0, 1);
            },
            sortProperty: 'name'
        },
        listeners: [
            {
                fn: 'onArraystoreLoad',
                event: 'load'
            }
        ]
    },

    onArraystoreLoad: function(store, records, successful, operation, eOpts) {
            //console.log("Store load success? " + successful );
           // console.log(operation);
    }

});