/*
 * File: app/view/ColleaguePanel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PixonicTeam.view.ColleaguePanel', {
    extend: 'Ext.Panel',
    alias: 'widget.colleaguepanel',

    requires: [
        'Ext.Spacer',
        'Ext.Label'
    ],

    config: {
        hidden: false,
        id: 'colleaguePanel',
        layout: {
            type: 'vbox',
            align: 'center'
        },
        items: [
            {
                xtype: 'spacer',
                height: 20,
                width: 20
            },
            {
                xtype: 'label',
                html: 'Details!',
                id: 'myLabel2',
                itemId: 'myLabel2'
            }
        ]
    },

    setInfo: function(record) {
            var label = this.getComponent('myLabel2');
            label.setHtml(record.data.lastname);
    }

});