/*
 * File: app/view/ColleaguePanel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PixonicTeam.view.ColleaguePanel', {
    extend: 'Ext.Panel',
    alias: 'widget.colleaguepanel',

    requires: [
        'Ext.Panel',
        'Ext.Spacer',
        'Ext.Img',
        'Ext.Label',
        'Ext.Button',
        'Ext.XTemplate'
    ],

    config: {
        fullscreen: true,
        hidden: false,
        id: 'colleaguePanel',
        layout: 'fit',
        items: [
            {
                xtype: 'panel',
                id: 'mainCnt',
                layout: 'vbox',
                scrollable: 'vertical',
                items: [
                    {
                        xtype: 'container',
                        height: '360px',
                        layout: {
                            type: 'vbox',
                            align: 'center'
                        },
                        items: [
                            {
                                xtype: 'spacer',
                                height: 10,
                                id: 'spacer1',
                                width: 50
                            },
                            {
                                xtype: 'image',
                                height: 300,
                                id: 'profilePhoto',
                                width: 300,
                                src: 'http://alphachan.org/b/thumb/132656219997.png?key=api'
                            },
                            {
                                xtype: 'container',
                                id: 'profileName',
                                layout: {
                                    type: 'vbox',
                                    align: 'center'
                                },
                                items: [
                                    {
                                        xtype: 'spacer',
                                        height: 10,
                                        id: 'spacer2',
                                        width: 10
                                    },
                                    {
                                        xtype: 'label',
                                        cls: 'list-item-header',
                                        height: '30px',
                                        html: 'Холин Роман',
                                        id: 'nameLabel'
                                    },
                                    {
                                        xtype: 'label',
                                        cls: [
                                            'post',
                                            'halign-center'
                                        ],
                                        height: '30px',
                                        html: 'Гейм-дизайнер',
                                        id: 'postLabel'
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        height: '100px',
                        id: 'contactsCnt',
                        style: 'border-top: 2px solid rgb(195,195,195); border-bottom: 2px solid rgb(195,195,195);',
                        layout: 'hbox',
                        items: [
                            {
                                xtype: 'button',
                                flex: 1,
                                cls: 'transparent',
                                html: '<div> 	<span style = "font-size: 16px; font-weight: bold"> E-mail: <span class ="mail-url" style="color: blue"> {email}</span> </span></br> 	<span style = "font-size: 16px; font-weight: bold"> Телефон: <span class ="phone-url" style="color: blue"> {email}</span> </span></br> 	<span style = "font-size: 16px; font-weight: bold"> Skype: <span class ="skype-url" style="color: blue"> {skype}</span> </span></br> 	<span style = "font-size: 16px; font-weight: bold">  Офис: <span style="font-weight: normal; color: rgb(140,140,140)"> {office}</span> </span> </div>',
                                id: 'contactsBtn',
                                labelCls: 'contacts-label',
                                text: 'MyButton10'
                            },
                            {
                                xtype: 'label',
                                hidden: true,
                                id: 'contactsLabel',
                                tpl: Ext.create('Ext.XTemplate', 
                                    '<div style="padding:5px 0px 5px 0px; font-size: 16px">',
                                    '    <span class="colleague-info"> E-mail: <a href="mailto:{email}?call" class = "colleague-info-hyperlink"> {email}</a></span><br>',
                                    '    <span class="colleague-info"> Телефон: <a href="tel:{[this.getNumbersFromPhone(values.phone)]}" class = "colleague-info-hyperlink"> {phone}</a></span><br>',
                                    '    <span class="colleague-info"> Skype: <a href="skype:{skype}?call" class = "colleague-info-hyperlink"> {skype}</a></span><br>',
                                    '    <span class="colleague-info"> Офис: <span style = "font-weight: normal; color: rgb(140,140,140)"> {office}</span></span>',
                                    '</div>',
                                    {
                                        getNumbersFromPhone: function(phone) {
                                            var digits = mainController.parsePhoneForCall(phone);
                                            console.log('Parsed phone '+ digits);
                                            return digits;

                                        }
                                    }
                                )
                            }
                        ]
                    },
                    {
                        xtype: 'label',
                        height: '',
                        id: 'infoLabel',
                        minHeight: '30px'
                    },
                    {
                        xtype: 'container',
                        height: '80px',
                        id: 'socialsCnt',
                        style: 'border-top: 2px solid rgb(195,195,195)',
                        layout: {
                            type: 'hbox',
                            pack: 'center'
                        },
                        items: [
                            {
                                xtype: 'image',
                                height: 75,
                                id: 'instagramBtn',
                                itemId: 'myimg1',
                                width: 75,
                                src: 'resources/css/images/buttons/insta.active.png'
                            },
                            {
                                xtype: 'image',
                                height: 75,
                                id: 'facebookBtn',
                                itemId: 'myimg2',
                                width: 75,
                                src: 'resources/css/images/buttons/fb.active.png'
                            },
                            {
                                xtype: 'image',
                                height: 75,
                                id: 'vkBtn',
                                itemId: 'myimg4',
                                width: 75,
                                src: 'resources/css/images/buttons/vk.active.png'
                            },
                            {
                                xtype: 'image',
                                height: 75,
                                id: 'twitterBtn',
                                itemId: 'myimg3',
                                style: 'background-repeat: no-repeat',
                                width: 75,
                                src: 'resources/css/images/buttons/twitter.active.png'
                            }
                        ]
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onInstagramBtnTap',
                event: 'tap',
                delegate: '#instagramBtn'
            },
            {
                fn: 'onFacebookBtnTap',
                event: 'tap',
                delegate: '#facebookBtn'
            },
            {
                fn: 'onVkBtnTap',
                event: 'tap',
                delegate: '#vkBtn'
            },
            {
                fn: 'onTwitterBtnTap',
                event: 'tap',
                delegate: '#twitterBtn'
            }
        ]
    },

    onInstagramBtnTap: function(image, e, eOpts) {
            this.onSocialButtonTap(image.getData());
    },

    onFacebookBtnTap: function(image, e, eOpts) {
            this.onSocialButtonTap(image.getData());
    },

    onVkBtnTap: function(image, e, eOpts) {
            this.onSocialButtonTap(image.getData());
    },

    onTwitterBtnTap: function(image, e, eOpts) {
                this.onSocialButtonTap(image.getData());
    },

    setInfo: function(record) {
           this.setData(record);
            var contactsLabel = Ext.getCmp('contactsLabel');
            String.prototype.replaceAll = function(search, replacement) {
                var target = this;
                return target.replace(new RegExp(search, 'g'), replacement);
            };
            var nameLabel =this.down('#profileName').down('#nameLabel');
            nameLabel.setHtml(record.data.name);
            var postLabel =this.down('#profileName').down('#postLabel');
            postLabel.setHtml(record.data.post);
            contactsLabel.setData(record.data);
            var infoLabel = Ext.getCmp('infoLabel');
            var infoHtml = '<div style = "padding: 0px 10px 0px 10px"> <span style = "font-weight: bold; ">Доп. информация: <span style = "font-weight: normal; font-size: 14px"> {info}</div>';
            infoLabel.setHtml(infoHtml.replace("{info}",record.data.info));
            this.updateSocialButtons(record);
    },

    onSocialButtonTap: function(data) {
            if (!data)
                return;

            if (!data["id"])
                return;

            var url =  data["id"];
            mainController.openUrl(url, true);
    },

    updateSocialButtons: function(record) {
            var twBtn = Ext.getCmp('twitterBtn');
            twBtn.setData({"id" : record.data.idTwitter});
            var twSrc = "resources/css/images/buttons/twitter.active.png"
            if (!record.data.idTwitter)
                twSrc = twSrc.replace("active","disabled");

            twBtn.setSrc(twSrc);

            var vkBtn = Ext.getCmp('vkBtn');
            vkBtn.setData({"id" : record.data.idVKontakte});
            var vkSrc = "resources/css/images/buttons/vk.active.png"
            if (!record.data.idVKontakte)
                vkSrc = vkSrc.replace("active","disabled");

            vkBtn.setSrc(vkSrc);



            var fbBtn = Ext.getCmp('facebookBtn');
            fbBtn.setData({"id" : record.data.idFacebook});
            var fbSrc = "resources/css/images/buttons/fb.active.png"
            if (!record.data.idFacebook)
                fbSrc = fbSrc.replace("active","disabled");

            fbBtn.setSrc(fbSrc);

            var instBtn = Ext.getCmp('instagramBtn');
            instBtn.setData({"id" : record.data.idInstagram});
            var instSrc = "resources/css/images/buttons/insta.active.png"
            if (!record.data.idInstagram)
                instSrc = instSrc.replace("active","disabled");

            instBtn.setSrc(instSrc);

    }

});