/*
 * File: app/view/EmployeesNav.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PixonicTeam.view.EmployeesNav', {
    extend: 'Ext.navigation.View',

    requires: [
        'Ext.navigation.Bar',
        'Ext.Button',
        'Ext.field.Search',
        'Ext.Label',
        'Ext.dataview.List',
        'Ext.XTemplate'
    ],

    config: {
        id: 'employeeNav',
        navigationBar: {
            docked: 'top',
            id: 'navBar',
            itemId: 'navBar',
            items: [
                {
                    xtype: 'button',
                    action: 'menuButtonPressed',
                    id: 'menuBtnNav',
                    itemId: 'menuBtnNav',
                    text: 'Меню'
                }
            ]
        },
        items: [
            {
                xtype: 'container',
                title: 'Сотрудники',
                id: 'searchContainer',
                layout: 'vbox',
                items: [
                    {
                        xtype: 'searchfield',
                        height: '40px',
                        id: 'employeeSearch',
                        itemId: 'employeeSearch',
                        placeHolder: 'Поиск'
                    },
                    {
                        xtype: 'label',
                        height: '40px',
                        html: 'По алфавиту'
                    },
                    {
                        xtype: 'list',
                        flex: 1,
                        id: 'employeeList1',
                        itemId: 'mylist1',
                        itemTpl: [
                            '<div>{lastname}</div>'
                        ],
                        store: 'EmployeeStore',
                        grouped: true,
                        striped: true
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onMynavigationbarBack',
                event: 'back',
                delegate: '#navBar'
            },
            {
                fn: 'onSearchfieldKeyup',
                event: 'keyup',
                delegate: '#employeeSearch'
            },
            {
                fn: 'onEmployeeSearchClearicontap',
                event: 'clearicontap',
                delegate: '#employeeSearch'
            },
            {
                fn: 'onEmployeeListItemTap1',
                event: 'itemtap',
                delegate: '#employeeList1'
            }
        ]
    },

    onMynavigationbarBack: function(bar, eOpts) {
            var menuBtn = Ext.getCmp('menuBtnNav');
            menuBtn.show();
    },

    onSearchfieldKeyup: function(textfield, e, eOpts) {
            var searchString = textfield.getValue();
            var store = Ext.getStore('EmployeeStore');
            store.clearFilter();
            if(searchString){
                var thisRegEx = new RegExp(searchString, "i");
                store.filterBy(function(record) {
                    return (thisRegEx.test(record.get('lastname')));
                });
            }
    },

    onEmployeeSearchClearicontap: function(textfield, e, eOpts) {
                Ext.getStore('EmployeeStore').clearFilter();
    },

    onEmployeeListItemTap1: function(dataview, index, target, record, e, eOpts) {
            var menuBtn = Ext.getCmp('menuBtnNav');
            menuBtn.hide();
             setTimeout(function(){dataview.deselect(index);},500);
            var panel = Ext.create('PixonicTeam.view.ColleaguePanel', {
                title: 'Сотрудники'
            });

            panel.setInfo(record);
            this.push(panel);
    }

});