/*
 * File: app/view/LoginPanel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PixonicTeam.view.LoginPanel', {
    extend: 'Ext.Panel',
    alias: 'widget.loginpanel',

    requires: [
        'Ext.Container',
        'Ext.Label',
        'Ext.Button'
    ],

    config: {
        id: 'loginPanel',
        items: [
            {
                xtype: 'container',
                layout: {
                    type: 'vbox',
                    align: 'center'
                },
                items: [
                    {
                        xtype: 'label',
                        html: 'Добро пожаловать в PixonicTeam! Войдите, используя аккаунт @pixonic.ru',
                        id: 'helloLabel',
                        padding: '50 0 50 0',
                        style: 'text-align: center'
                    },
                    {
                        xtype: 'label',
                        cls: 'x-label-error',
                        id: 'errorLabel'
                    },
                    {
                        xtype: 'button',
                        action: 'confirm',
                        baseCls: 'google-button-active',
                        height: 46,
                        id: 'loginBtn',
                        width: 191,
                        pressedCls: 'google-button-pressed'
                    }
                ]
            }
        ]
    }

});