/*
 * File: app/view/MainToolbar.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PixonicTeam.view.MainToolbar', {
    extend: 'Ext.Toolbar',
    alias: 'widget.mainToolbar',

    requires: [
        'Ext.Button'
    ],

    config: {
        docked: 'top',
        id: 'mainToolbar',
        items: [
            {
                xtype: 'button',
                action: 'menuButtonPressed',
                id: 'menuBtn',
                text: 'Меню'
            }
        ]
    }

});