/*
 * File: app/view/ProfilePanel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PixonicTeam.view.ProfilePanel', {
    extend: 'Ext.Panel',
    alias: 'widget.profilePanel',

    requires: [
        'Ext.Spacer',
        'Ext.Button'
    ],

    config: {
        hidden: false,
        id: 'profilePanel',
        layout: {
            type: 'vbox',
            align: 'center'
        },
        items: [
            {
                xtype: 'spacer',
                height: 20,
                width: 20
            },
            {
                xtype: 'button',
                action: 'logout',
                height: 40,
                padding: '',
                width: 150,
                text: 'Выйти'
            }
        ]
    }

});