/*
 * File: app/view/ProfilePanel.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PixonicTeam.view.ProfilePanel', {
    extend: 'Ext.Panel',
    alias: 'widget.profilePanel',

    requires: [
        'PixonicTeam.view.ProfileInfo',
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.Spacer'
    ],

    config: {
        hidden: false,
        id: 'profilePanel',
        layout: 'fit',
        items: [
            {
                xtype: 'toolbar',
                cls: 'toolbar',
                docked: 'top',
                id: 'profileToolbar',
                ui: 'light',
                title: 'Профиль',
                layout: {
                    type: 'hbox',
                    align: 'end'
                },
                items: [
                    {
                        xtype: 'button',
                        action: 'menuButtonPressed',
                        text: 'Меню'
                    }
                ]
            },
            {
                xtype: 'spacer',
                height: 20,
                width: 20
            },
            {
                xtype: 'profileinfo',
                docked: 'top',
                id: 'myInfo'
            }
        ]
    },

    updateInfo: function() {
            var info = this.down('#myInfo');
            info.setInfo(this.getData());
    }

});