/*
 * File: app/view/SlidingMenu.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PixonicTeam.view.SlidingMenu', {
    extend: 'Ext.Menu',

    requires: [
        'Ext.Button'
    ],

    config: {
        style: 'bodyStyle:\'background-color:red !important;\'',
        width: 250,
        layout: 'vbox',
        items: [
            {
                xtype: 'button',
                action: 'menuItemPressed',
                cls: 'menu-button',
                height: '65px',
                id: 'profileMenuItem',
                icon: 'resources/css/images/icon.profile.png',
                iconCls: 'profile-icon',
                labelCls: 'menu-label',
                text: 'ПРОФИЛЬ'
            },
            {
                xtype: 'button',
                action: 'menuItemPressed',
                cls: 'menu-button',
                height: '60px',
                id: 'calendarMenuItem',
                icon: 'resources/css/images/icon.calendar.png',
                iconCls: 'profile-icon',
                labelCls: 'menu-label',
                text: 'КАЛЕНДАРЬ'
            },
            {
                xtype: 'button',
                action: 'menuItemPressed',
                cls: 'menu-button',
                height: '60px',
                id: 'employeesMenuItem',
                icon: 'resources/css/images/icon.calendar.png',
                iconCls: 'profile-icon',
                labelCls: 'menu-label',
                text: 'СОТРУДНИКИ'
            }
        ]
    }

});