/*
 * File: app/controller/LoginController.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PixonicTeam.controller.LoginController', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            loginBtn: '#loginBtn'
        },

        control: {
            "[action=confirm]": {
                tap: 'onButtonTap'
            }
        }
    },

    onButtonTap: function(button, e, eOpts) {
        var params = 'client_id=' + encodeURIComponent(clientId);
        params += '&redirect_uri='+encodeURIComponent("http://localhost:1841");
        params += '&response_type=code';
        params += '&scope=' + encodeURIComponent(scopes);
        var authUrl = 'https://accounts.google.com/o/oauth2/auth?' + params;
        var win = window.open(authUrl, '_blank', 'location=no,toolbar=no,width=800, height=800');
        //this.checkAuth(false);
    },

    checkAuth: function(immediate) {
            console.log("trying login with immediate " + immediate);
            gapi.auth.authorize({client_id: clientId, scope: scopes, immediate: immediate}, this.handleAuthResult);
    },

    handleAuthResult: function(result) {
         if (result && !result.error) {
             console.log("Auth OK, token" + result.access_token);
         } else {
             console.log("AUth ERROR"+ result.error);
         }
    },

    launch: function() {
                console.log('launch controller');
                gapi.client.setApiKey(apiKey);

    },

    loadCalendarApi: function() {
        gapi.client.load('calendar', 'v3', listUpcomingEvents);

    },

    listUpcomingEvents: function() {

    }

});