/*
 * File: app/controller/MainController.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PixonicTeam.controller.MainController', {
    extend: 'Ext.app.Controller',

    requires: [
        'PixonicTeam.view.SlidingMenu',
        'PixonicTeam.view.ProfilePanel',
        'PixonicTeam.view.CalendarPanel'
    ],

    config: {
        control: {
            "[action=menuButtonPressed]": {
                tap: 'onMenuButtonTap'
            },
            "[action=menuItemPressed]": {
                tap: 'onMenuItemPressed'
            },
            "listitem": {
                onListItemTap: 'OnListItemTap'
            },
            "[action /=/(?:menu)/]": {
                tap: 'onButtonTap'
            }
        }
    },

    onMenuButtonTap: function(button, e, eOpts) {
        var menus = Ext.Viewport.getMenus();
        if (Ext.Viewport.getMenus().left.isHidden()){
            Ext.Viewport.showMenu('left');
        }
        else {
            Ext.Viewport.hideMenu('left');
        }

    },

    onMenuItemPressed: function(button, e, eOpts) {
            this.showPanel(button.id);
    },

    OnListItemTap: function(listitem) {

    },

    onButtonTap: function(button, e, eOpts) {
            console.log('Its not menu opening button');
            Ext.Viewport.hideMenu('left');
    },

    launch: function() {
            console.log('creating menu');
            mainController = this;
            var toolbar = Ext.create('PixonicTeam.view.MainToolbar');
            toolbar.hide();
            Ext.Viewport.add(toolbar);

            Ext.Viewport.setMenu(Ext.create('PixonicTeam.view.SlidingMenu'), {
                side: 'left',
                reveal: false
            });

            Ext.Viewport.add(Ext.create('PixonicTeam.view.ProfilePanel'));
            Ext.Viewport.add(Ext.create('PixonicTeam.view.CalendarPanel'));

            Ext.Viewport.add(Ext.create('PixonicTeam.view.EmployeesNav'));

    },

    showPanel: function(panelName) {
            console.log('menu item pressed ' + panelName);
            var tab, title;
            var bar = Ext.getCmp('mainToolbar');
            switch(panelName){
                case 'profileMenuItem': {
                    title = 'Профиль';
                    tab = Ext.getCmp('profilePanel');
                    bar.show();
                    break;
                }
                case 'calendarMenuItem': {
                    title = 'Календарь';
                    tab = Ext.getCmp('calendarPanel');
                    bar.show();
                    break;
                }
                case 'employeesMenuItem': {
                    title = 'Сотрудники';
                    tab = Ext.getCmp('employeeNav');
                    bar.hide();
                    break;
                }

                case 'colleaguePanel': {
                    title = 'Сотрудники';
                    bar.hide();
                    tab = Ext.getCmp('colleaguePanel');
                    break;
                }
                default:
                    break;
            }

            bar.setTitle(title);
            Ext.Viewport.hideMenu('left');
            Ext.Viewport.setActiveItem(tab);
    }

});