/*
 * File: app/model/Employee.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PixonicTeam.model.Employee', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field'
    ],

    config: {
        fields: [
            {
                name: 'name',
                type: 'string'
            },
            {
                name: 'email',
                type: 'string'
            },
            {
                name: 'office',
                type: 'string'
            },
            {
                name: 'post',
                type: 'string'
            },
            {
                name: 'phone',
                type: 'string'
            },
            {
                name: 'skype',
                type: 'string'
            },
            {
                name: 'photo',
                type: 'string'
            },
            {
                name: 'idFacebook',
                type: 'string'
            },
            {
                name: 'idInstagram',
                type: 'string'
            },
            {
                name: 'idTwitter',
                type: 'string'
            },
            {
                name: 'idVKontakte',
                type: 'string'
            },
            {
                name: 'holidayBegin',
                type: 'string'
            },
            {
                name: 'holidayEnd',
                type: 'string'
            },
            {
                name: 'regDate',
                type: 'string'
            },
            {
                name: 'info',
                type: 'string'
            }
        ]
    }
});